### ISSUE TITLE
LV.3 Личный кабинет волонтера: LV.3.1 Просмотр анкеты волонтера

### ISSUE THREAD

**Issue by Julia-Papina** [volunteers-for-city-projects/volunteers-frontend#12]
Хорошо бы отказаться от варфреймов и делать сразу в цвете чтобы не переделывать

- [x] Сверстать компоненты анкеты волонтера согласно дизайну (в цвете) 1920
- [x] Сверстать страницу анкеты волонтера согласно дизайну (в цвете) 1920
- [x] Сверстать компоненты анкеты волонтера согласно дизайну (в цвете) 1366
- [x] Сверстать страницу анкеты волонтера согласно дизайну (в цвете) 1366

**Comment by Julia-Papina** [comment]
ЛК без раздела Проекты

**Comment by kseniia2673** [comment]
изменение пароля в задаче по редактированию
