### ISSUE TITLE
LO.4 Личный кабинет организатора: LO.4.1 Просмотр анкеты организатора

### ISSUE THREAD

**Issue by Julia-Papina** [volunteers-for-city-projects/volunteers-frontend#13]
Хорошо бы отказаться от варфреймов и делать сразу в цвете

- [x] Сверстать компоненты анкеты организатора согласно дизайну (в цвете) 1920
- [x] Сверстать страницу анкеты организатора согласно дизайну (в цвете) 1920
- [x] Сверстать компоненты анкеты организатора согласно дизайну (в цвете) 1366
- [x] Сверстать страницу анкеты организатора согласно дизайну (в цвете) 1366

**Comment by kseniia2673** [comment]
изменение пароля в задаче по редактированию
