### ISSUE TITLE
G.1.1 Просмотр главной страницы: изменения

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-frontend#133]
- [x] капча в форме ОС

- [x] убрать блок стать волонтером/организатором у авторизованного пользователя

- [x] добавить чек - бокс с согласием на обработку персональных данных в форме ОС после кнопки "Оставить заявку" (чек-бокс можно взять из формы регистрации).
- [x] #145

**Comment by EvgeniiyaR** [comment]
Привет, не поняла, что имеется в виду под появившейся последней задачей "подвинуть 1 блок, чтобы влезали счетчики по проектам"

**Comment by kseniia2673** [comment]
Привет, это ты сама себе задачу ставила, добавили сюда тк тоже относится к изменениям на главной
