### ISSUE TITLE
Шрифт ошибок на экране регистрации волонтера и организатора больше 15px и накладывается на соседние элементы при разрешении 1366х768

### ISSUE THREAD

**Issue by danilastepanov** [volunteers-for-city-projects/volunteers-frontend#222]
### **Шаги воспроизведения:**

1. Открыть страницу регистрации волонтера / организатора [https://better-together.acceleratorpracticum.ru/#/registration/volunteer](https://better-together.acceleratorpracticum.ru/#/registration/volunteer) / [https://better-together.acceleratorpracticum.ru/#/registration/organizer](https://better-together.acceleratorpracticum.ru/#/registration/organizer)
2. Ввести в поля количество символов больше разрешенного

### **Ожидаемый результат:**

Текст ошибки выводится на одной строке. Размер шрифта 15px

### **Фактический результат:**

Текст ошибки переносится. Размер шрифта 20px

### **Окружение:**

* URL:  [http://better-together.acceleratorpracticum.ru/](http://better-together.acceleratorpracticum.ru/)
* Браузер: Chrome 108.0.5359.125 (64-bit) (1366х768), Яндекс Браузер 22.9.3.886 (1366х768)
* ОС: Windows 11 22000.1098

### Приложение:
![image](https://github.com/volunteers-for-city-projects/volunteers-frontend/assets/32541462/1a5f40ff-cc2c-491b-9002-2e31dcc01134)
![image](https://github.com/volunteers-for-city-projects/volunteers-frontend/assets/32541462/2ab57ab8-9249-4066-915d-6b9b3f3ced5f)
![image](https://github.com/volunteers-for-city-projects/volunteers-frontend/assets/32541462/abb835d0-7232-4090-bc17-325cf614c637)

![image](https://github.com/volunteers-for-city-projects/volunteers-frontend/assets/32541462/e8baad1b-b11c-47f0-92b7-5a83f6c9acef)
![image](https://github.com/volunteers-for-city-projects/volunteers-frontend/assets/32541462/498fdc15-93fd-4d38-8f06-bb875384c4f8)
![image](https://github.com/volunteers-for-city-projects/volunteers-frontend/assets/32541462/3d20d03d-a841-4f16-99f3-6cdff7d9ceeb)

**Comment by DBKai** [comment]
Поправил

**Comment by danilastepanov** [comment]
Проверил, закрыл
