### ISSUE TITLE
Если название проекта на странице проекта не переносится на вторую строку, то пропадет расстояние между блоком с картинкой и блоком с информацией о проекте

### ISSUE THREAD

**Issue by danilastepanov** [volunteers-for-city-projects/volunteers-frontend#223]
### **Шаги воспроизведения:**

1. Открыть страницы проектов https://better-together.acceleratorpracticum.ru/#/projects/99 / https://better-together.acceleratorpracticum.ru/#/projects/4

### **Ожидаемый результат:**

Между блоком с картинкой и блоком с информацией о проекте есть отступ.

### **Фактический результат:**

Между блоком с картинкой и блоком с информацией о проекте нет отступа, если название проекта умещается на одной строке.

### **Окружение:**

* URL:  [http://better-together.acceleratorpracticum.ru/](http://better-together.acceleratorpracticum.ru/)
* Браузер: Chrome 108.0.5359.125 (64-bit) (1366х768 / 1920х1080), Яндекс Браузер 22.9.3.886 (1366х768 / 1920х1080)
* ОС: Windows 11 22000.1098

### Приложение:

https://github.com/volunteers-for-city-projects/volunteers-frontend/assets/32541462/541c3fad-5d68-4012-ab48-57ee2480ce9f

https://github.com/volunteers-for-city-projects/volunteers-frontend/assets/32541462/7d626a53-e41f-41d2-a318-23914b7618fa

**Comment by DBKai** [comment]
Поправил

**Comment by danilastepanov** [comment]
Проверил. закрыл.
