### ISSUE TITLE
Разное расстояние между элементами в анкете организатора в личном кабинете (1366х768 и 1920х1080)

### ISSUE THREAD

**Issue by danilastepanov** [volunteers-for-city-projects/volunteers-frontend#224]
### **Шаги воспроизведения:**

1. Авторизоваться в роли организатора
2. Зайти в личный кабинет

### **Ожидаемый результат:**

Отступы между элементами в анкете равны 20px.

### **Фактический результат:**

Отступы между элементами в анкете имеют разное значение.

### **Окружение:**

* URL:  [http://better-together.acceleratorpracticum.ru/](http://better-together.acceleratorpracticum.ru/)
* Браузер: Chrome 108.0.5359.125 (64-bit) (1366х768 и 1920х1080), Яндекс Браузер 22.9.3.886 (1366х768 и 1920х1080)
* ОС: Windows 11 22000.1098

### Приложение:
![image](https://github.com/volunteers-for-city-projects/volunteers-frontend/assets/32541462/72dec459-c7f2-44bb-aee1-6a46dea7a581)

![image](https://github.com/volunteers-for-city-projects/volunteers-frontend/assets/32541462/f8bdf8d3-2d4a-468c-b5ae-510ffa2a9131)
![image](https://github.com/volunteers-for-city-projects/volunteers-frontend/assets/32541462/a40b8404-34b4-4f04-a3fb-2d3710ef55a1)

**Comment by Julia-Papina** [comment]
Исправлено

**Comment by danilastepanov** [comment]
Перепроверил. Закрыл.
