### ISSUE TITLE
G.1 Главная страница: G.1.1 Просмотр главной страницы

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-frontend#26]
Подзадачи к фиче G.1.1 Просмотр главной страницы:

- [x] Верстка отдельных компонентов по варфреймам 1920
- [x] Сборка главной страницы по варфреймам 1920
- [x] Верстка отдельных компонентов согласно дизайну в цвете 1920 
- [x] Верстка модала выхода согласно дизайну в цвете 1920
- [x] Верстка хэдер согласно дизайну в цвете 1920
- [x] Верстка футер согласно дизайну в цвете 1920
- [x] Верстка бади согласно дизайну в цвете 1920
- [x] Сборка главной страницы согласно дизайну в цвете 1920
- [x] Верстка отдельных компонентов согласно дизайну в цвете 1366
- [x] Верстка модала выхода согласно дизайну в цвете 1366
- [x] Верстка хэдер согласно дизайну в цвете 1366
- [x] Верстка футер согласно дизайну в цвете 1366
- [x] Верстка бади согласно дизайну в цвете 1366
- [x] Сборка главной страницы согласно дизайну в цвете 1366
- [x] Добиться функционирования всех линков и кнопок - открытие страниц по ссылкам в меню (пусть пока пустых)
- [x] Функционирование формы ОС
- [x] Пуши ОС (отправлено, не отправлено)

**Comment by vvn1982** [comment]
Еще можно добавитьзадачи по улучшению - устранение проблем с шириной хедера-футера на маленьком экране, устранение уползания новостей в браузере Firefox, по возможности верстка для двух значений ширины 13хх и 19хх
