### ISSUE TITLE
R.5 Регистрация:R.5.2 Регистрация организатора

### ISSUE THREAD

**Issue by kseniia2673** [volunteers-for-city-projects/volunteers-frontend#32]
- [x] Верстка отдельных компонентов формы регистрации организатора по варфреймам 1920 @VanVorobyov 

- [x] Сборка страницы регистрации организатора по варфреймам 1920 @VanVorobyov 

- [x] Составить Post запросы @VanVorobyov 

- [x] Верстка отдельных компонентов регистрации организатора в дизайне 1920

- [x] компонент ввода текста @VanVorobyov 
- [x] компонент выбора даты @VanVorobyov 
- [x] компонент ввода пароля @VanVorobyov 
- [x] компонент ввода эл.почты @VanVorobyov 
- [x] компонент ввода телефона @VanVorobyov 
- [x] сверстать свитчер (волонтер/организатор) @VanVorobyov 
- [x] сверстать компонент множественного выбора из списка @DBKai 
- [x] компонент выпадающий список @DBKai 

- [x] Сборка формы регистрации организатора в дизайне 1920 @VanVorobyov 

- [x] Верстка отдельных компонентов регистрации организатора в дизайне 1366 

- [x] Сборка формы регистрации организатора в дизайне 1366

**Comment by VanVorobyov** [comment]
Страница регистрации организатора в разрешении 1920 готова

**Comment by kseniia2673** [comment]
https://github.com/volunteers-for-city-projects/volunteers-frontend/pull/47

**Comment by kseniia2673** [comment]
- [x] компонент добавления фото (значок, мини-фото и функционал)@EvgeniiyaR 

- [x] Модальные окна подтверждения регистрации @vvkon13
